package com.dmitriim.localailab.core.model.manifest

import kotlinx.serialization.Serializable

/** Semantic role of an installed model file. Adapters may define additional roles. */
@Serializable
@JvmInline
value class ModelFileRole(val value: String) {
    companion object {
        val PRIMARY_MODEL = ModelFileRole("PRIMARY_MODEL")
        val ENCODER = ModelFileRole("ENCODER")
        val DECODER = ModelFileRole("DECODER")
        val JOINER = ModelFileRole("JOINER")
        val MERGED_DECODER = ModelFileRole("MERGED_DECODER")
        val PREPROCESSOR = ModelFileRole("PREPROCESSOR")
        val UNCACHED_DECODER = ModelFileRole("UNCACHED_DECODER")
        val CACHED_DECODER = ModelFileRole("CACHED_DECODER")
        val TOKENS = ModelFileRole("TOKENS")
        val DURATION_PREDICTOR = ModelFileRole("DURATION_PREDICTOR")
        val TEXT_ENCODER = ModelFileRole("TEXT_ENCODER")
        val VECTOR_ESTIMATOR = ModelFileRole("VECTOR_ESTIMATOR")
        val VOCODER = ModelFileRole("VOCODER")
        val CONFIG = ModelFileRole("CONFIG")
        val UNICODE_INDEXER = ModelFileRole("UNICODE_INDEXER")
        val VOICE_STYLE = ModelFileRole("VOICE_STYLE")
        val LICENSE = ModelFileRole("LICENSE")
        val VITS_MODEL = ModelFileRole("VITS_MODEL")
        val FRONTEND_DATA = ModelFileRole("FRONTEND_DATA")
        val KOKORO_MODEL = ModelFileRole("KOKORO_MODEL")
        val VOICE_EMBEDDINGS = ModelFileRole("VOICE_EMBEDDINGS")
        val LEXICON = ModelFileRole("LEXICON")
        val TEXT_RULES = ModelFileRole("TEXT_RULES")
        val DICTIONARY_DATA = ModelFileRole("DICTIONARY_DATA")
        val LM_FLOW = ModelFileRole("LM_FLOW")
        val LM_MAIN = ModelFileRole("LM_MAIN")
        val POCKET_ENCODER = ModelFileRole("POCKET_ENCODER")
        val POCKET_DECODER = ModelFileRole("POCKET_DECODER")
        val TEXT_CONDITIONER = ModelFileRole("TEXT_CONDITIONER")
        val VOCABULARY = ModelFileRole("VOCABULARY")
        val TOKEN_SCORES = ModelFileRole("TOKEN_SCORES")
        val REFERENCE_AUDIO = ModelFileRole("REFERENCE_AUDIO")
        val SPEECH_ENCODER = ModelFileRole("SPEECH_ENCODER")
        val EMBED_TOKENS = ModelFileRole("EMBED_TOKENS")
        val LANGUAGE_MODEL = ModelFileRole("LANGUAGE_MODEL")
        val CONDITIONAL_DECODER = ModelFileRole("CONDITIONAL_DECODER")
        val EXTERNAL_DATA = ModelFileRole("EXTERNAL_DATA")
        val TOKENIZER = ModelFileRole("TOKENIZER")
    }
}

object ModelFileRoles {
    val PRIMARY_MODEL = ModelFileRole("PRIMARY_MODEL")
    val ENCODER = ModelFileRole("ENCODER")
    val DECODER = ModelFileRole("DECODER")
    val JOINER = ModelFileRole("JOINER")
    val MERGED_DECODER = ModelFileRole("MERGED_DECODER")
    val PREPROCESSOR = ModelFileRole("PREPROCESSOR")
    val UNCACHED_DECODER = ModelFileRole("UNCACHED_DECODER")
    val CACHED_DECODER = ModelFileRole("CACHED_DECODER")
    val TOKENS = ModelFileRole("TOKENS")
    val DURATION_PREDICTOR = ModelFileRole("DURATION_PREDICTOR")
    val TEXT_ENCODER = ModelFileRole("TEXT_ENCODER")
    val VECTOR_ESTIMATOR = ModelFileRole("VECTOR_ESTIMATOR")
    val VOCODER = ModelFileRole("VOCODER")
    val CONFIG = ModelFileRole("CONFIG")
    val UNICODE_INDEXER = ModelFileRole("UNICODE_INDEXER")
    val VOICE_STYLE = ModelFileRole("VOICE_STYLE")
    val LICENSE = ModelFileRole("LICENSE")
    val VITS_MODEL = ModelFileRole("VITS_MODEL")
    val FRONTEND_DATA = ModelFileRole("FRONTEND_DATA")
    val KOKORO_MODEL = ModelFileRole("KOKORO_MODEL")
    val VOICE_EMBEDDINGS = ModelFileRole("VOICE_EMBEDDINGS")
    val LEXICON = ModelFileRole("LEXICON")
    val TEXT_RULES = ModelFileRole("TEXT_RULES")
    val DICTIONARY_DATA = ModelFileRole("DICTIONARY_DATA")
    val LM_FLOW = ModelFileRole("LM_FLOW")
    val LM_MAIN = ModelFileRole("LM_MAIN")
    val POCKET_ENCODER = ModelFileRole("POCKET_ENCODER")
    val POCKET_DECODER = ModelFileRole("POCKET_DECODER")
    val TEXT_CONDITIONER = ModelFileRole("TEXT_CONDITIONER")
    val VOCABULARY = ModelFileRole("VOCABULARY")
    val TOKEN_SCORES = ModelFileRole("TOKEN_SCORES")
    val REFERENCE_AUDIO = ModelFileRole("REFERENCE_AUDIO")
    val SPEECH_ENCODER = ModelFileRole("SPEECH_ENCODER")
    val EMBED_TOKENS = ModelFileRole("EMBED_TOKENS")
    val LANGUAGE_MODEL = ModelFileRole("LANGUAGE_MODEL")
    val CONDITIONAL_DECODER = ModelFileRole("CONDITIONAL_DECODER")
    val EXTERNAL_DATA = ModelFileRole("EXTERNAL_DATA")
    val TOKENIZER = ModelFileRole("TOKENIZER")
}
