package com.dmitriim.localailab.ai.api.chat

/** One structured message supplied to an engine chat template or caller-owned formatter. */
data class LlmChatMessage(val role: LlmChatRole, val content: String)

/** Roles understood by the engine-neutral chat contract. */
enum class LlmChatRole(val wireName: String) {
    /** A conversation-wide instruction that precedes user and assistant turns. */
    SYSTEM("system"),
    /** A turn authored by the person using the app. */
    USER("user"),
    /** A completed turn generated by the model. */
    ASSISTANT("assistant"),
}
