package com.dmitriim.localailab.source.models.catalog.stt

import com.dmitriim.localailab.core.model.capability.AiCapability
import com.dmitriim.localailab.core.model.engine.EngineId
import com.dmitriim.localailab.core.model.library.CatalogArchiveFormat
import com.dmitriim.localailab.core.model.library.CatalogDownload
import com.dmitriim.localailab.core.model.library.CatalogDownloadArchive
import com.dmitriim.localailab.core.model.library.CatalogModel
import com.dmitriim.localailab.core.model.library.ModelCatalogState
import com.dmitriim.localailab.core.model.manifest.ModelFileRoles
import com.dmitriim.localailab.core.model.manifest.ModelFileSpec
import com.dmitriim.localailab.core.model.manifest.ModelFormat
import com.dmitriim.localailab.core.model.manifest.ModelId
import com.dmitriim.localailab.core.model.manifest.ModelManifest
import com.dmitriim.localailab.core.model.manifest.ModelProfileIds
import com.dmitriim.localailab.core.model.manifest.ModelSource
import com.dmitriim.localailab.core.model.manifest.SttRecognitionMode
import com.dmitriim.localailab.source.models.catalog.CatalogDefaults

internal object ArchiveSttModelCatalog {
    val entries: List<CatalogModel> = listOf(
        sttArchiveModel(
            modelId = "parakeet-tdt-ctc-110m-en-int8",
            displayName = "Parakeet TDT-CTC 110M INT8",
            family = "Parakeet",
            description = "An English offline speech-to-text model quantized to INT8.",
            profileType = ModelProfileIds.PARAKEET_CTC_STT,
            archiveName = "sherpa-onnx-nemo-parakeet_tdt_ctc_110m-en-36000-int8",
            archiveBytes = 104_337_827,
            archiveSha256 = "17f945007b52ccd8b7200ffc7c5652e9e8e961dfdf479cefcabd06cf5703630b",
            files = listOf(
                ModelFileSpec("model.int8.onnx", ModelFileRoles.PRIMARY_MODEL, expectedBytes = 131_652_171),
                ModelFileSpec("tokens.txt", ModelFileRoles.TOKENS, expectedBytes = 9_953),
            ),
            languages = linkedSetOf("English"),
            licenseName = "CC-BY-4.0",
            attribution = "NVIDIA Parakeet TDT-CTC 110M, converted and packaged for sherpa-onnx.",
            approximateRamBytes = 500_000_000,
        ),
        sttArchiveModel(
            modelId = "gigaam-v2-ctc-ru-int8",
            displayName = "GigaAM v2 CTC INT8",
            family = "GigaAM",
            description = "A Russian offline speech-to-text model quantized to INT8.",
            profileType = ModelProfileIds.GIGAAM_CTC_STT,
            archiveName = "sherpa-onnx-nemo-ctc-giga-am-v2-russian-2025-04-19",
            archiveBytes = 166_917_722,
            archiveSha256 = "777be8717d8aaf04861823671290f7687f7579fd9ac63a2124955573f920caf5",
            files = listOf(
                ModelFileSpec("model.int8.onnx", ModelFileRoles.PRIMARY_MODEL, expectedBytes = 236_457_977),
                ModelFileSpec("tokens.txt", ModelFileRoles.TOKENS, expectedBytes = 196),
            ),
            languages = linkedSetOf("Russian"),
            licenseName = "MIT",
            attribution = "GigaAM v2 by SberDevices, converted and packaged for sherpa-onnx.",
            approximateRamBytes = 800_000_000,
        ),
        sttArchiveModel(
            modelId = "zipformer-en-20m-streaming-int8",
            displayName = "Zipformer 20M Streaming INT8",
            family = "Zipformer",
            description = "An English streaming speech-to-text model quantized to INT8.",
            profileType = ModelProfileIds.ZIPFORMER_STT,
            archiveName = "sherpa-onnx-streaming-zipformer-en-20M-2023-02-17",
            archiveBytes = 127_887_156,
            archiveSha256 = "9c559283e8498d3fe95913c79ca1cb454bb26281ac2b102b41306c7d752765d9",
            files = listOf(
                ModelFileSpec("encoder-epoch-99-avg-1.int8.onnx", ModelFileRoles.ENCODER, expectedBytes = 42_845_182),
                ModelFileSpec("decoder-epoch-99-avg-1.int8.onnx", ModelFileRoles.DECODER, expectedBytes = 539_499),
                ModelFileSpec("joiner-epoch-99-avg-1.int8.onnx", ModelFileRoles.JOINER, expectedBytes = 259_572),
                ModelFileSpec("tokens.txt", ModelFileRoles.TOKENS, expectedBytes = 5_048),
            ),
            languages = linkedSetOf("English"),
            licenseName = "Apache-2.0",
            attribution = "Icefall streaming Zipformer model packaged for sherpa-onnx.",
            recognitionMode = SttRecognitionMode.STREAMING,
            approximateRamBytes = 350_000_000,
        ),
        sttArchiveModel(
            modelId = "sensevoice-small-5lang-int8",
            displayName = "SenseVoice Small INT8",
            family = "SenseVoice",
            description = "An offline speech-to-text model supporting Chinese, English, Japanese, Korean, and Cantonese.",
            profileType = ModelProfileIds.SENSE_VOICE_STT,
            archiveName = "sherpa-onnx-sense-voice-zh-en-ja-ko-yue-int8-2024-07-17",
            archiveBytes = 163_002_883,
            archiveSha256 = "7d1efa2138a65b0b488df37f8b89e3d91a60676e416f515b952358d83dfd347e",
            files = listOf(
                ModelFileSpec("model.int8.onnx", ModelFileRoles.PRIMARY_MODEL),
                ModelFileSpec("tokens.txt", ModelFileRoles.TOKENS),
            ),
            languages = linkedSetOf("Chinese", "English", "Japanese", "Korean", "Cantonese"),
            licenseName = "See upstream model license",
            attribution = "SenseVoiceSmall by FunAudioLLM, converted and packaged for sherpa-onnx.",
            approximateRamBytes = 700_000_000,
        ),
        sttArchiveModel(
            modelId = "paraformer-zh-en-small-int8",
            displayName = "Paraformer Small INT8",
            family = "Paraformer",
            description = "A Chinese-and-English offline speech-to-text model quantized to INT8.",
            profileType = ModelProfileIds.PARAFORMER_STT,
            archiveName = "sherpa-onnx-paraformer-zh-small-2024-03-09",
            archiveBytes = 77_920_048,
            archiveSha256 = "da92b3db5218c5be53aad53e57d1b6e63e7fc98a0e054fbdd6dbe18e9c6b1450",
            files = listOf(
                ModelFileSpec("model.int8.onnx", ModelFileRoles.PRIMARY_MODEL, expectedBytes = 81_828_675),
                ModelFileSpec("tokens.txt", ModelFileRoles.TOKENS, expectedBytes = 75_352),
            ),
            languages = linkedSetOf("Chinese", "English"),
            licenseName = "Apache-2.0",
            attribution = "Paraformer model from ModelScope, converted and packaged for sherpa-onnx.",
            approximateRamBytes = 350_000_000,
        ),
        sttArchiveModel(
            modelId = "moonshine-tiny-en-int8",
            displayName = "Moonshine Tiny English INT8",
            family = "Moonshine",
            description = "A compact English offline speech-to-text model quantized to INT8.",
            profileType = ModelProfileIds.MOONSHINE_V1_STT,
            archiveName = "sherpa-onnx-moonshine-tiny-en-int8",
            archiveBytes = 107_600_538,
            archiveSha256 = "d5fe6ec4334fef36255b2a4010412cad4c007e33103fec62fb5d17cad88086f2",
            files = listOf(
                ModelFileSpec("preprocess.onnx", ModelFileRoles.PREPROCESSOR, expectedBytes = 6_800_738),
                ModelFileSpec("encode.int8.onnx", ModelFileRoles.ENCODER, expectedBytes = 18_249_187),
                ModelFileSpec("uncached_decode.int8.onnx", ModelFileRoles.UNCACHED_DECODER, expectedBytes = 53_216_096),
                ModelFileSpec("cached_decode.int8.onnx", ModelFileRoles.CACHED_DECODER, expectedBytes = 45_264_830),
                ModelFileSpec("tokens.txt", ModelFileRoles.TOKENS, expectedBytes = 436_688),
            ),
            languages = linkedSetOf("English"),
            licenseName = "MIT",
            attribution = "Moonshine Tiny by Useful Sensors, converted and packaged for sherpa-onnx.",
            approximateRamBytes = 350_000_000,
        ),
        sttArchiveModel(
            modelId = "moonshine-base-en-quantized",
            displayName = "Moonshine v2 Base Quantized",
            family = "Moonshine",
            description = "A quantized English offline speech-to-text model.",
            profileType = ModelProfileIds.MOONSHINE_STT,
            archiveName = "sherpa-onnx-moonshine-base-en-quantized-2026-02-27",
            archiveBytes = 111_266_225,
            archiveSha256 = "43232c1d13013d37317163baec3135bd771a186a4356f28c889bab453bb0e891",
            files = listOf(
                ModelFileSpec("encoder_model.ort", ModelFileRoles.ENCODER, expectedBytes = 31_326_816),
                ModelFileSpec("decoder_model_merged.ort", ModelFileRoles.MERGED_DECODER, expectedBytes = 109_424_400),
                ModelFileSpec("tokens.txt", ModelFileRoles.TOKENS, expectedBytes = 549_350),
            ),
            languages = linkedSetOf("English"),
            licenseName = "CC-BY-4.0",
            attribution = "Moonshine v2 by Useful Sensors, quantized and packaged for sherpa-onnx.",
            approximateRamBytes = 550_000_000,
        ),
        sttArchiveModel(
            modelId = "vosk-small-en-us-0-15",
            displayName = "Vosk Small English US",
            family = "Vosk",
            description = "A lightweight streaming speech-to-text model for US English.",
            engineId = EngineId("vosk"),
            profileType = ModelProfileIds.VOSK_STT,
            archiveName = "vosk-model-small-en-us-0.15",
            downloadUrl = "https://alphacephei.com/vosk/models/vosk-model-small-en-us-0.15.zip",
            archiveBytes = 41_205_931,
            archiveSha256 = "30f26242c4eb449f948e42cb302dd7a686cb29a3423a8367f99ff41780942498",
            archiveFormat = CatalogArchiveFormat.ZIP,
            files = voskDirectories(),
            languages = linkedSetOf("English"),
            licenseName = "Apache-2.0",
            attribution = "Vosk lightweight US English model by Alpha Cephei.",
            recognitionMode = SttRecognitionMode.STREAMING,
            quantization = null,
            approximateRamBytes = 300_000_000,
        ),
        sttArchiveModel(
            modelId = "vosk-small-ru-0-22",
            displayName = "Vosk Small Russian",
            family = "Vosk",
            description = "A lightweight streaming speech-to-text model for Russian.",
            engineId = EngineId("vosk"),
            profileType = ModelProfileIds.VOSK_STT,
            archiveName = "vosk-model-small-ru-0.22",
            downloadUrl = "https://alphacephei.com/vosk/models/vosk-model-small-ru-0.22.zip",
            archiveBytes = 46_236_750,
            archiveSha256 = "961d5ff98a17f4aa6de69864d0aa71fa5bac682301d2b5d17a3f24c5c99a46d4",
            archiveFormat = CatalogArchiveFormat.ZIP,
            files = voskDirectories(),
            languages = linkedSetOf("Russian"),
            licenseName = "Apache-2.0",
            attribution = "Vosk lightweight Russian model by Alpha Cephei.",
            recognitionMode = SttRecognitionMode.STREAMING,
            quantization = null,
            approximateRamBytes = 300_000_000,
        ),
    )

    private fun sttArchiveModel(
        modelId: String,
        displayName: String,
        family: String,
        description: String,
        profileType: com.dmitriim.localailab.core.model.manifest.ModelProfileId,
        archiveName: String,
        archiveBytes: Long,
        archiveSha256: String,
        files: List<ModelFileSpec>,
        languages: Set<String>,
        licenseName: String,
        attribution: String,
        approximateRamBytes: Long,
        engineId: EngineId = EngineId("sherpa-onnx"),
        downloadUrl: String = "https://github.com/k2-fsa/sherpa-onnx/releases/download/asr-models/$archiveName.tar.bz2",
        archiveFormat: CatalogArchiveFormat = CatalogArchiveFormat.TAR_BZIP2,
        recognitionMode: SttRecognitionMode = SttRecognitionMode.OFFLINE,
        quantization: String? = "INT8",
    ) = CatalogModel(
        manifest = ModelManifest(
            modelId = ModelId(modelId),
            displayName = displayName,
            family = family,
            description = description,
            capabilities = setOf(AiCapability.SPEECH_TO_TEXT),
            engineId = engineId,
            profileType = profileType,
            format = if (engineId.value == "vosk") ModelFormat.BINARY else ModelFormat.ONNX,
            quantization = quantization,
            architecture = family,
            revision = archiveName.substringAfterLast('-'),
            files = files,
            source = ModelSource(
                url = downloadUrl,
                revision = archiveName,
                licenseName = licenseName,
                attribution = attribution,
            ),
            languages = languages,
            supportedLanguageCount = languages.size,
            sampleRateHz = 16_000,
            sttRecognitionMode = recognitionMode,
            approximateRamBytes = approximateRamBytes,
            catalogVersion = CatalogDefaults.VERSION,
            installedAtEpochMs = 0,
        ),
        state = ModelCatalogState.APPROVED,
        download = CatalogDownload(
            expectedBytes = archiveBytes,
            archive = CatalogDownloadArchive(
                url = downloadUrl,
                expectedBytes = archiveBytes,
                sha256 = archiveSha256,
                rootDirectory = archiveName,
                format = archiveFormat,
            ),
        ),
    )

    private fun voskDirectories() = listOf(
        ModelFileSpec("am", ModelFileRoles.PRIMARY_MODEL, directory = true),
        ModelFileSpec("conf", ModelFileRoles.CONFIG, directory = true),
        ModelFileSpec("graph", ModelFileRoles.VOCABULARY, directory = true),
    )
}
