package com.dmitriim.localaiplayground.source.models.catalog.chat

import com.dmitriim.localaiplayground.core.model.capability.AiCapability
import com.dmitriim.localaiplayground.core.model.engine.EngineId
import com.dmitriim.localaiplayground.core.model.library.CatalogDownload
import com.dmitriim.localaiplayground.core.model.library.CatalogModel
import com.dmitriim.localaiplayground.core.model.library.ModelCatalogState
import com.dmitriim.localaiplayground.core.model.manifest.ModelFileRoles
import com.dmitriim.localaiplayground.core.model.manifest.ModelFileSpec
import com.dmitriim.localaiplayground.core.model.manifest.ModelFormat
import com.dmitriim.localaiplayground.core.model.manifest.ModelId
import com.dmitriim.localaiplayground.core.model.manifest.ModelManifest
import com.dmitriim.localaiplayground.core.model.manifest.ModelProfileIds
import com.dmitriim.localaiplayground.core.model.manifest.ModelSource
import com.dmitriim.localaiplayground.source.models.catalog.CatalogDefaults

internal object ChatModelCatalog {
    val entries: List<CatalogModel> = listOf(
        llmModel(
            modelId = "qwen3-1.7b-q4-k-m",
            displayName = "Qwen3 1.7B Q4_K_M",
            family = "Qwen3",
            description = "A 1.7B multilingual chat model packaged as a Q4_K_M GGUF for local text generation.",
            repository = "ggml-org/Qwen3-1.7B-GGUF",
            revision = "daeb8e2d528a760970442092f6bf1e55c3b659eb",
            fileName = "Qwen3-1.7B-Q4_K_M.gguf",
            quantization = "Q4_K_M",
            expectedBytes = 1_282_439_264,
            sha256 = "d2387ca2dbfee2ffabce7120d3770dadca0b293052bc2f0e138fdc940d9bc7b5",
            languages = linkedSetOf("English", "Russian", "Chinese"),
            supportedLanguageCount = 119,
            approximateRamBytes = 2_300_000_000,
            state = ModelCatalogState.APPROVED,
        ),
        llmModel(
            modelId = "qwen3.5-0.8b-q4-0",
            displayName = "Qwen3.5 0.8B Q4_0",
            family = "Qwen3.5",
            description = "A compact 0.8B English-and-Chinese chat model packaged as a Q4_0 GGUF.",
            repository = "ggml-org/Qwen3.5-0.8B-GGUF",
            revision = "8fea620810c4afa23dd6443f999a48574c1611a3",
            fileName = "Qwen3.5-0.8B-Q4_0.gguf",
            quantization = "Q4_0",
            expectedBytes = 563_036_064,
            sha256 = "57d1997790d1744fba5b40a7317df71ea5e2acee28c47e78f0cce39c0703f8cf",
            languages = linkedSetOf("English", "Chinese"),
            approximateRamBytes = 1_200_000_000,
        ),
        llmModel(
            modelId = "lfm2.5-1.2b-instruct-q4-k-m",
            displayName = "LFM2.5 1.2B Instruct Q4_K_M",
            family = "LFM2.5",
            description = "A 1.2B instruction-tuned chat model covering eight catalogued languages in Q4_K_M format.",
            repository = "LiquidAI/LFM2.5-1.2B-Instruct-GGUF",
            revision = "047e06635fbe71469926b35ea414537245218200",
            fileName = "LFM2.5-1.2B-Instruct-Q4_K_M.gguf",
            quantization = "Q4_K_M",
            expectedBytes = 730_895_168,
            sha256 = "b1b3de114215d9507409a662a501a631095a479a419584e8a2ded6304b19b4f5",
            languages = linkedSetOf("English", "Arabic", "Chinese", "French", "German", "Japanese", "Korean", "Spanish"),
            supportedLanguageCount = 8,
            approximateRamBytes = 1_500_000_000,
            licenseName = "LFM Open License v1.0",
            attribution = "LFM2.5 by Liquid AI; use is subject to the LFM Open License v1.0.",
        ),
        llmModel(
            modelId = "llama-3.2-1b-instruct-q4-k-m",
            displayName = "Llama 3.2 1B Instruct Q4_K_M",
            family = "Llama 3.2",
            description = "A compact 1B instruction-tuned chat model covering eight catalogued languages.",
            repository = "bartowski/Llama-3.2-1B-Instruct-GGUF",
            revision = "067b946cf014b7c697f3654f621d577a3e3afd1c",
            fileName = "Llama-3.2-1B-Instruct-Q4_K_M.gguf",
            quantization = "Q4_K_M",
            expectedBytes = 807_694_464,
            sha256 = "6f85a640a97cf2bf5b8e764087b1e83da0fdb51d7c9fab7d0fece9385611df83",
            languages = linkedSetOf("English", "German", "French", "Italian", "Portuguese", "Hindi", "Spanish", "Thai"),
            supportedLanguageCount = 8,
            approximateRamBytes = 1_500_000_000,
            licenseName = "Llama 3.2 Community License",
            attribution = "Llama 3.2 by Meta; quantized GGUF by bartowski. The Llama 3.2 Community License applies.",
        ),
        llmModel(
            modelId = "gemma-3-1b-it-q4-k-m",
            displayName = "Gemma 3 1B IT Q4_K_M",
            family = "Gemma 3",
            description = "A compact 1B instruction-tuned multilingual chat model packaged as a Q4_K_M GGUF.",
            repository = "ggml-org/gemma-3-1b-it-GGUF",
            revision = "f9c28bcd85737ffc5aef028638d3341d49869c27",
            fileName = "gemma-3-1b-it-Q4_K_M.gguf",
            quantization = "Q4_K_M",
            expectedBytes = 806_058_240,
            sha256 = "8ccc5cd1f1b3602548715ae25a66ed73fd5dc68a210412eea643eb20eb75a135",
            languages = linkedSetOf("English", "Russian", "Chinese"),
            supportedLanguageCount = 140,
            approximateRamBytes = 1_600_000_000,
            licenseName = "Gemma Terms of Use",
            attribution = "Gemma 3 by Google; use is subject to the Gemma Terms of Use and Prohibited Use Policy.",
        ),
        llmModel(
            modelId = "deepseek-r1-distill-qwen-1.5b-q4-k-m",
            displayName = "DeepSeek R1 Distill Qwen 1.5B Q4_K_M",
            family = "DeepSeek R1 Distill Qwen",
            description = "A 1.5B distilled English-and-Chinese chat model packaged as a Q4_K_M GGUF.",
            repository = "bartowski/DeepSeek-R1-Distill-Qwen-1.5B-GGUF",
            revision = "9cc28b17e86fa2415fcb070f8ee5ec27c965aa61",
            fileName = "DeepSeek-R1-Distill-Qwen-1.5B-Q4_K_M.gguf",
            quantization = "Q4_K_M",
            expectedBytes = 1_117_320_800,
            sha256 = "1741e5b2d062b07acf048bf0d2c514dadf2a48f94e2b4aa0cfe069af3838ee2f",
            languages = linkedSetOf("English", "Chinese"),
            supportedLanguageCount = 2,
            approximateRamBytes = 2_100_000_000,
            licenseName = "MIT",
            attribution = "DeepSeek R1 Distill Qwen by DeepSeek; quantized GGUF by bartowski. MIT licensed.",
        ),
        llmModel(
            modelId = "smollm3-3b-q4-k-m",
            displayName = "SmolLM3 3B Q4_K_M",
            family = "SmolLM3",
            description = "A 3B multilingual chat model covering six catalogued languages in Q4_K_M format.",
            repository = "ggml-org/SmolLM3-3B-GGUF",
            revision = "4965cb60b150737b68a0408c36aeefb65078f894",
            fileName = "SmolLM3-Q4_K_M.gguf",
            quantization = "Q4_K_M",
            expectedBytes = 1_915_305_312,
            sha256 = "8334b850b7bd46238c16b0c550df2138f0889bf433809008cc17a8b05761863e",
            languages = linkedSetOf("English", "French", "Spanish", "German", "Italian", "Portuguese"),
            supportedLanguageCount = 6,
            approximateRamBytes = 3_200_000_000,
        ),
        llmModel(
            modelId = "llama-3.2-3b-instruct-q4-k-m",
            displayName = "Llama 3.2 3B Instruct Q4_K_M",
            family = "Llama 3.2",
            description = "A 3B instruction-tuned chat model covering eight catalogued languages in Q4_K_M format.",
            repository = "bartowski/Llama-3.2-3B-Instruct-GGUF",
            revision = "5ab33fa94d1d04e903623ae72c95d1696f09f9e8",
            fileName = "Llama-3.2-3B-Instruct-Q4_K_M.gguf",
            quantization = "Q4_K_M",
            expectedBytes = 2_019_377_696,
            sha256 = "6c1a2b41161032677be168d354123594c0e6e67d2b9227c84f296ad037c728ff",
            languages = linkedSetOf("English", "German", "French", "Italian", "Portuguese", "Hindi", "Spanish", "Thai"),
            supportedLanguageCount = 8,
            approximateRamBytes = 3_400_000_000,
            licenseName = "Llama 3.2 Community License",
            attribution = "Llama 3.2 by Meta; quantized GGUF by bartowski. The Llama 3.2 Community License applies.",
        ),
        llmModel(
            modelId = "phi-4-mini-instruct-q4-k-m",
            displayName = "Phi-4 Mini Instruct Q4_K_M",
            family = "Phi-4 Mini",
            description = "A multilingual instruction-tuned chat model packaged as a Q4_K_M GGUF.",
            repository = "unsloth/Phi-4-mini-instruct-GGUF",
            revision = "78eb92a46fc37e6b524df991ed9aca9bc6aa7b80",
            fileName = "Phi-4-mini-instruct-Q4_K_M.gguf",
            quantization = "Q4_K_M",
            expectedBytes = 2_491_874_272,
            sha256 = "88c00229914083cd112853aab84ed51b87bdf6b9ce42f532d8c85c7c63b1730a",
            languages = linkedSetOf("English", "Chinese", "French", "German", "Russian", "Spanish"),
            supportedLanguageCount = 23,
            approximateRamBytes = 4_000_000_000,
            licenseName = "MIT",
            attribution = "Phi-4 Mini by Microsoft; quantized GGUF by Unsloth. MIT licensed.",
        ),
    )

    private fun llmModel(
        modelId: String,
        displayName: String,
        family: String,
        description: String,
        repository: String,
        revision: String,
        fileName: String,
        quantization: String,
        expectedBytes: Long,
        sha256: String,
        languages: Set<String>,
        approximateRamBytes: Long,
        supportedLanguageCount: Int? = null,
        licenseName: String = "Apache-2.0",
        attribution: String = CatalogDefaults.APACHE_ATTRIBUTION,
        state: ModelCatalogState = ModelCatalogState.OPTIONAL,
    ): CatalogModel {
        val downloadUrl = "https://huggingface.co/$repository/resolve/$revision/$fileName"
        val sourceUrl = "https://huggingface.co/$repository/tree/$revision"
        return CatalogModel(
            manifest = ModelManifest(
                modelId = ModelId(modelId),
                displayName = displayName,
                family = family,
                description = description,
                capabilities = setOf(AiCapability.CHAT),
                engineId = EngineId("llama.cpp"),
                profileType = ModelProfileIds.LLM,
                format = ModelFormat.GGUF,
                quantization = quantization,
                architecture = family,
                revision = revision,
                files = listOf(
                    ModelFileSpec(
                        relativePath = fileName,
                        role = ModelFileRoles.PRIMARY_MODEL,
                        expectedBytes = expectedBytes,
                        sha256 = sha256,
                    ),
                ),
                source = ModelSource(
                    url = sourceUrl,
                    revision = revision,
                    licenseName = licenseName,
                    attribution = attribution,
                ),
                languages = languages,
                supportedLanguageCount = supportedLanguageCount,
                contextSize = 512,
                approximateRamBytes = approximateRamBytes,
                catalogVersion = CatalogDefaults.VERSION,
                installedAtEpochMs = 0,
            ),
            state = state,
            download = CatalogDownload(
                url = downloadUrl,
                expectedBytes = expectedBytes,
                sha256 = sha256,
            ),
        )
    }
}
